# Generated by Django 2.2.3 on 2019-07-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='', max_length=200)),
                ('nesbatJari', models.IntegerField(default=0)),
                ('nesbatAni', models.IntegerField(default=0)),
            ],
        ),
    ]
