# Generated by Django 2.2.3 on 2019-07-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='company',
            name='nesbatAni',
        ),
        migrations.RemoveField(
            model_name='company',
            name='nesbatJari',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='FinancialRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentRatio', models.IntegerField(null=True)),
                ('quickRatio', models.IntegerField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Company')),
                ('financialYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.FinancialYear')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Industry')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Category'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Industry'),
        ),
    ]
